comment out code to focus on docker image

diff --git a/.github/workflows/optimize-release-optimize-c8-only.yml b/.github/workflows/optimize-release-optimize-c8-only.yml
--- a/.github/workflows/optimize-release-optimize-c8-only.yml
+++ b/.github/workflows/optimize-release-optimize-c8-only.yml
@@ -169,60 +169,60 @@ jobs:
             --fail-at-end \
             -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
 
-      - name: Push changes
-        if: env.IS_DRY_RUN == 'false'
-        run: |
-          git push --tags
-          git push --all
+      # - name: Push changes
+      #   if: env.IS_DRY_RUN == 'false'
+      #   run: |
+      #     git push --tags
+      #     git push --all
 
-      - name: Perform release
-        run: |
-          mvn -f optimize \
-            -DlocalCheckout=true \
-            -DskipTests=true \
-            -B \
-            --fail-at-end \
-            -Prelease,engine-latest \
-            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
-            release:perform \
-            -Darguments="-Dmaven.deploy.skip=${IS_DRY_RUN} -DskipTests -DskipNexusStagingDeployMojo=${IS_DRY_RUN} -B --fail-at-end -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -f pom.xml"
+      # - name: Perform release
+      #   run: |
+      #     mvn -f optimize \
+      #       -DlocalCheckout=true \
+      #       -DskipTests=true \
+      #       -B \
+      #       --fail-at-end \
+      #       -Prelease,engine-latest \
+      #       -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
+      #       release:perform \
+      #       -Darguments="-Dmaven.deploy.skip=${IS_DRY_RUN} -DskipTests -DskipNexusStagingDeployMojo=${IS_DRY_RUN} -B --fail-at-end -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -f pom.xml"
 
-      - name: Remove tag for RC release
-        if: env.IS_RC == 'true'
-        run: |
-          git tag -d ${TAG}
-          git push origin :refs/tags/${TAG}
+      # - name: Remove tag for RC release
+      #   if: env.IS_RC == 'true'
+      #   run: |
+      #     git tag -d ${TAG}
+      #     git push origin :refs/tags/${TAG}
 
-      - name: Auto-update previous version
-        run: |
-          if [ "$IS_PATCH" = "false" ]; then
-            # only major / minor GA (.0) release versions will trigger an auto-update of previousVersion property.
-            echo "Auto-updating previousVersion property as release version is a valid major/minor version."
-            git fetch
-            git checkout ${BRANCH}
-            sed -i "s/project.previousVersion>.*</project.previousVersion>${RELEASE_VERSION}</g" pom.xml
-            git add pom.xml
-            # This is needed to not abort the job in case 'git diff' returns a status different from 0
-            set +e
-            git diff --staged --quiet
-            diff_result=$?
-            set -e
+      # - name: Auto-update previous version
+      #   run: |
+      #     if [ "$IS_PATCH" = "false" ]; then
+      #       # only major / minor GA (.0) release versions will trigger an auto-update of previousVersion property.
+      #       echo "Auto-updating previousVersion property as release version is a valid major/minor version."
+      #       git fetch
+      #       git checkout ${BRANCH}
+      #       sed -i "s/project.previousVersion>.*</project.previousVersion>${RELEASE_VERSION}</g" pom.xml
+      #       git add pom.xml
+      #       # This is needed to not abort the job in case 'git diff' returns a status different from 0
+      #       set +e
+      #       git diff --staged --quiet
+      #       diff_result=$?
+      #       set -e
 
-            if [ $diff_result -ne 0 ]; then
-              git commit -m "chore: update previousVersion to new release version ${RELEASE_VERSION}"
-              echo "pushing to branch ${BRANCH}"
-              if [ "$IS_DRY_RUN" = "true" ]; then
-                echo "not pushing to branch ${BRANCH} in dry run mode"
-              else
-                echo "pushing to branch ${BRANCH}"
-                git push origin ${BRANCH}
-              fi
-            else
-              echo "Release version ${RELEASE_VERSION} did not change. Nothing to commit."
-            fi
-          else
-            echo "Not auto-updating previousVersion property as release version is not a valid major/minor version."
-          fi
+      #       if [ $diff_result -ne 0 ]; then
+      #         git commit -m "chore: update previousVersion to new release version ${RELEASE_VERSION}"
+      #         echo "pushing to branch ${BRANCH}"
+      #         if [ "$IS_DRY_RUN" = "true" ]; then
+      #           echo "not pushing to branch ${BRANCH} in dry run mode"
+      #         else
+      #           echo "pushing to branch ${BRANCH}"
+      #           git push origin ${BRANCH}
+      #         fi
+      #       else
+      #         echo "Release version ${RELEASE_VERSION} did not change. Nothing to commit."
+      #       fi
+      #     else
+      #       echo "Not auto-updating previousVersion property as release version is not a valid major/minor version."
+      #     fi
 
       - name: Build Docker Image
         run: |
